sudo: required
services:
  - docker
language: bash

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build alpine
  - chmod +x ./bootstrap.sh
  - docker run --rm --privileged -v ${TRAVIS_BUILD_DIR}:/host/ -e GITHUB_ACCESS_TOKEN="${GITHUB_ACCESS_TOKEN}" multiarch/alpine:armhf-edge /host/bootstrap.sh
    
after_success:
  - echo "Done!"
