sudo: required
services:
  - docker
language: bash

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build alpine
  - chmod +x ./build.sh
  - docker run --rm -v ./:/host/ multiarch/alpine:armhf-edge /host/build.sh
    
after_success:
  - echo "Done!"
