sudo: required
dist: trusty
# This attribute does not matter. We just choose some less popular language
# to don't hog resources and further increase the wait time for other people
# who use a more popular language / runtime.
language: erlang

script:
  - set -eo pipefail
  - chmod +x ./build.sh
  - sudo ./build.sh
