sudo: required
services:
  - docker
language: bash

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build alpine
  - chmod +x ./build.sh
  - ./build.sh
    
after_success:
  - echo "Done!"
